name: 'Manage pushed locales from client'
description: 'Close stale PRs and open new PR for pushed branch'
inputs:
  baseBranch:
    description: 'Base branch of the repository. Defaults is "master".'
    required: false
    default: 'master'
  branchPattern:
    description: 'Branches to match when searching for related PRs'
    required: true
  prTemplateTitle:
    description: 'Title of new pull requests'
    required: true
  prTemplateBody:
    description: 'Body of new pull requests'
    required: true
outputs:
  closed-prs:
    description: 'PR numbers of all closed PRs'
  opened-pr:
    description: 'PR number of the opened PR'
runs:
  using: 'node16'
  main: 'dist/index.js'
