name: Translations PR Wrangler Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - 'track-fe-app-*'

jobs:
  manage-prs-for-pushed-locales:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/actions
    steps:
      - name: Checkout repository and build actions
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '>=12.16.2'
      - run: yarn && yarn build
      - name: Manage pushed locales
        uses: ./.github/actions/packages/manage-pushed-locales
        with:
          branch-pattern: track-fe-app-*
          pr-template-title: "[track-fe-app] Update locales pushed from client"
          pr-template-body: |
            These are the latest changes pushed from the client.

            This PR superseded the following PRs:
            {CLOSED_PRS}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}