name: Translations PR Wrangler Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - 'track-fe-app-*'

jobs:
  manage-prs-for-pushed-locales:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and build actions
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@toggl'

      - name: Build actions
        run: yarn && yarn workspace run build

      - name: Manage pushed locales
        uses: ./.github/actions/packages/manage-pushed-locales
        with:
          branchPattern: track-fe-app-*
          prTemplateTitle: "[track-fe-app] Update locales pushed from client"
          prTemplateBody: |
            These are the latest changes pushed from the client.

            This PR superseded the following PRs:
            {CLOSED_PRS}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
