name: Seed Translations

on:
  workflow_dispatch:
    inputs:
      app:
        description: App translations to seed
        required: true
        type: choice
        options:
          - track/fe/app
      locale:
        description: Locale to seed
        required: true
        type: string

permissions:
  pull-requests: write

jobs:
  seed:
    name: Seed
    runs-on: ubuntu-latest
