name: Seed Translations

on:
  workflow_dispatch:
    inputs:
      app:
        description: App translations to seed
        required: true
        type: choice
        options:
          - track/fe/app
      locale:
        description: Locale to seed
        required: true
        type: string

permissions:
  pull-requests: write

jobs:
  seed:
    name: Seed
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .github/actions

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build actions
        run: yarn && yarn build
